Vagrant.configure("2") do |config|
    config.vm.box = "hashicorp/bionic64"
    
    config.vm.provider "virtualbox" do |v|
      v.name = "videojs-shaka"
    end
    
    config.vm.network "forwarded_port", guest: 3000, host: 3000
    config.vm.provision :shell, path: "provision/system.sh"
    config.vm.synced_folder ".", "/vagrant", disabled: true
    if Vagrant::Util::Platform.windows? then
        config.vm.synced_folder "../", "/vagrant", type: 'smb', mount_options: ["mfsymlinks"]
    else
        config.vm.synced_folder "../", "/vagrant"
    end
end
