Vagrant.configure("2") do |config|
    config.vm.box = "hashicorp/bionic64"
    
    config.vm.provider "virtualbox" do |v|
      v.name = "videojs-shaka"
      v.memory = 4096
      v.cpus = 4
    end
    
    config.vm.network "forwarded_port", guest: 3000, host: 3000
    config.vm.provision :shell, path: "provision/system.sh"
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.synced_folder "../", "/vagrant"
end
